/*

  Copyright (c) 2018 by Elena Marchenko, Institute of Volcanology and Seismology
  
 */

// References
var	contentReferences = `<h2>References</h2>
			   <p class="lorem">The map layers were created using the following data sources:</p>
			   \
			   <h4 style="margin-bottom:-6px">Active volcanoes and volcanic hazard zones</h4>
			   <p class="lorem">Markhinin E., Sirin A. et al.&nbsp;&nbsp 1962<br><a href="http://repo.kscnet.ru/3663/1/Marchinin_EK_BVS-32_1962.pdf" target="_blank">Experience of volcano-geographical zoning of Kamchatka and the Kuril Islands.</a> Bulletin of the Kamchatka Volcanological Station. vol 32. p. 52-70. (in Russian)</p>
			   \
			   <h4 style="margin-bottom:-6px">Sredinniy ridge: quaternary and holocene volcanoes</h4>
			   <p class="lorem">Ogorodov N., Kozhemyaka N.&nbsp;&nbsp 1972<br>Volcanoes and quaternary volcanism of the Sredinniy ridge of Kamchatka. ed. by Erlikh E., Moscow: Science — 191 p. (in Russian)</p>
			   \
			   <p class="lorem">Pevzner M.&nbsp;&nbsp 2015<br> Holocene volcanism of Sredinny Range of Kamchatka, ed. by M. Fedonkin. Transactions of the Geological Institute, vol. 608. Moscow: GEO — 252 p. (in Russian)
			   <a href="http://www.ginras.ru/library/pdf/608_pevzner2015_holocene_volcanism_kamchatka.pdf" target="_blank"> ISBN 978-5-89118-682-8</a></p>
			   \
			   <h4 style="margin-bottom:-6px">Kluchevskoy volcano: cinder cones and lava flows</h4>
			   <p class="lorem">Cinder cones and lava flows of lateral eruptions were mapped using sattelite images (LandSAT, ESRI Firefly) and dated based on:</p>
			   <p class="lorem">Ponomareva V., Melekestsev I., Braitseva O.&nbsp;&nbsp 2010<br>Quaternary volcanism on the Kamchatka Peninsula, Northwest Pacific Region. Eruptive history of Kluchevskoy volcano. Conference presentation. Russian-Japan expert meeting in Kamchatka, November 2010.</p>
			   \
			   <h4 style="margin-bottom:-6px">Maximum accumulation of seasonal snow (snow water equivalent)</h4>
			   <p class="lorem">Kotlyakov V., Kravtsova  V., Dreyer N.&nbsp;&nbsp 1997<br>The world atlas of snow and ice resources. Russian Academy of Sciences, Institute of Geography, vol.2 — 371 p. 
			   \
			   <h4 style="margin-bottom:-6px">Glaciers and moraine</h4>
			   <p class="lorem"><u>Sredinniy ridge</u>: Glaciers outlines were mapped using <a href="https://landsat.usgs.gov/" target="_blank">Landsat</a> Images (L7, L8 - August 2002, 2016) and orthophotoes taken from aircraft in 1949-1951. This dataset reflects glacial retreat in the Northern Kamchatka at the second part of 20th / beginning of 21st century.</p>
			   <p class="lorem"><u>Northern group of volcanoes</u>: Glaciers outlines were primarily mapped in 2010 using sattelite images (LandSAT, Aster) and has been updated a number of times since then. The latest update was done in September 2020 (ESRI Firefly Imagery - also available as a basemap "Sattelite"). In some cases the location of glaciers fronts were revised based on GPS measurements in the field.</p>
			   <p class="lorem">Vinogradov V.&nbsp;&nbsp 1968<br>The USSR glacier catalog. Kamchatka, vol. 20, part 2-4. Leningrad:Hydrometeorological service — 80 p. (in Russian)</p>
			   <h4 style="margin-bottom:-6px">Geological samples</h4>
			   <p class="lorem">Alves, S., Schiano, P., Capmas, F. and Allègre, C.J., 2002. <a href=https://doi.org/10.1016/S0012-821X(02)00524-1>Osmium isotope binary mixing arrays in arc volcanism</a>. Earth and Planetary Science Letters, 198(3), 355-369. .</p>
			   <p class="lorem">Andreev, V.I. and Topchieva, O.M., 2013. Mount Povorotnaya is a fragment of a stratovolcano located northeast of the Plosky Tolbachik volcano. In: E.I. Gordeev (Ed.) Volcanism and related processes. Regional scientific conference dedicated to the Day of the Volcanologist, Petropavlovsk-Kamchatsky, March 29-30, 2013. Materials of the conference. IVS FEB RAS, Petropavlovsk-Kamchatsky, pp. 15-19. http://www.kscnet.ru/ivs/publication/volc_day/2013/art2.pdf. (In Russian).</p>
			   <p class="lorem">Ariskin, A., Barmina, G., Ozerov, A. and Nielsen, R., 1995. Genesis of high-alumina basalts from Klyuchevskoi Volcano. Petrology, 3(5), 449-472. http://repo.kscnet.ru/3426/.</p>
			   <p class="lorem">Bindeman, I.N., Ponomareva, V.V., Bailey, J.C. and Valley, J.W., 2004. Volcanic arc of Kamchatka: a province with high-δ18O magma sources and large-scale 18O/16O depletion of the upper crust. Geochimica et Cosmochimica Acta, 68(4), 841-865. https://doi.org/10.1016/j.gca.2003.07.009.</p>
			   <p class="lorem">Bindeman, I.N., Eiler, J.M., Yogodzinski, G.M., Tatsumi, Y., Stern, C.R., Grove, T.L., Portnyagin, M., Hoernle, K. and Danyushevsky, L.V., 2005. Oxygen isotope evidence for slab melting in modern and ancient subduction zones. Earth and Planetary Science Letters, 235(3–4), 480-496. https://doi.org/10.1016/j.epsl.2005.04.014.</p>
			   <p class="lorem">Braitseva, O.A., Melekestsev, I.V., Flerov, G.B., Ponomareva, V.V., Sulerzhitsky, L.D. and Litasova, S.N., 1984. Holocene volcanism of the Tolbachik regional zone of cinder cones. In: S.A. Fedotov (Ed.) Large Tolbachik fissure eruption, Kamchatka, 1975-1976. Nauka, Moscow, pp. 177-223. http://www.kscnet.ru/ivs/bibl/srab/btti1975-1976.djvu. (In Russian).</p>
			   <p class="lorem">Braitseva, O.A., Melekestsev, I.V., Bogoyavlenskaya, G.E. and Maksimov, A.P., 1991. Bezymyannyi: eruptive history and dynamics. Volcanology and Seismology, 12(2), 165-194. http://repo.kscnet.ru/id/eprint/793.</p>
			   <p class="lorem">Bryant, J.A., Yogodzinski, G.M. and Churikova, T.G., 2007. Melt-mantle interactions beneath the Kamchatka arc: Evidence from ultramafic xenoliths from Shiveluch volcano. Geochemistry, Geophysics, Geosystems, 8(4): art. Q04007, 1-24. https://doi.org/10.1029/2006GC001443.</p>
			   <p class="lorem">Bryant, J.A., Yogodzinski, G.M. and Churikova, T.G., 2011. High-Mg# andesitic lavas of the Shisheisky Complex, Northern Kamchatka: implications for primitive calc-alkaline magmatism. Contributions to Mineralogy and Petrology, 161(5), 791-810. https://doi.org/10.1007/s00410-010-0565-4.</p>
			   <p class="lorem">Calkins, J.A., 2004. 40Ar/39Ar geochronology of Khapitsa plateau and Studyonaya river basalts and basaltic andesites in Central Kamchatka Depression, Kamchatka, Russia. In: E.I. Gordeev (Ed.) Linkages among Tectonics, Seismicity, Magma Genesis, and Eruption in Volcanic Arcs. IV International Biennial Workshop on Subduction Processes Emphasizing the Japan–Kurile–Kamchatka–Aleutian Arcs. Petropavlovsk-Kamchatsky, August 21-27, 2004. Institute of Volcanology and Seismology FEB RAS, Petropavlovsk-Kamchatsky, pp. 53-54. http://www.kscnet.ru/ivs/conferences/kasp/tez/ab21en.doc.</p>
			   <p class="lorem">Churikova, T.G. and Sokolov, S.Y., 1994. Sr isotope geochemistry and the magmatic evolution of Ploskiye Sopki volcano, Kamchatka. Geochemistry International, 31(5), 61-69. https://www.researchgate.net/publication/298199361.</p>
			   <p class="lorem">Churikova, T., Dorendorf, F. and Wörner, G., 2001. Sources and fluids in the mantle wedge below Kamchatka, evidence from across-arc geochemical variation. Journal of Petrology, 42(8), 1567-1593. https://doi.org/10.1093/petrology/42.8.1567.</p>
			   <p class="lorem">Churikova, T., Wörner, G., Eichelberger, J. and Ivanov, B., 2007a. Minor- and Trace Element Zoning in Plagioclase From Kizimen Volcano, Kamchatka: Insights on the Magma Chamber Processes. In: J. Eichelberger, E. Gordeev, P. Izbekov, M. Kasahara and J. Lees (Eds.), Volcanism and Subduction: The Kamchatka Region. Geophysical Monograph Series Vol. 172. American Geophysical Union, Washington, DC, pp. 303-323. http://doi.org/10.1029/172GM22.</p>
			   <p class="lorem">Churikova, T., Wörner, G., Mironov, N. and Kronz, A., 2007b. Volatile (S, Cl and F) and fluid mobile trace element compositions in melt inclusions: implications for variable fluid sources across the Kamchatka arc. Contributions to Mineralogy and Petrology, 154(2), 217-239. http://doi.org/10.1007/s00410-007-0190-z.</p>
			   <p class="lorem">Churikova, T.G., Gordeychik, B.N., Belousov, A.B. and Babansky, A.D., 2010. Find the centre of the eruption of basalts on the volcano Shiveluch. In: E.I. Gordeev (Ed.) Materials of All-Russian Conference Dedicated to the 75th Anniversary of the Kamchatka Volcanological Station. Petropavlovsk-Kamchatsky, September 9-15, 2010. Institute of Volcanology and Seismology FEB RAS, Petropavlovsk-Kamchatsky, pp. 102-105. http://www.kscnet.ru/ivs/slsecret/75-KVS/Material_conferenc/art25.pdf. (In Russian).</p>
			   <p class="lorem">Churikova, T.G., Gordeichik, B.N. and Ivanov, B.V., 2012. Petrochemistry of Kamen volcano: A comparison with neighboring volcanoes of the Klyuchevskoy group. Journal of Volcanology and Seismology, 6(3), 150-171. https://doi.org/10.1134/S0742046312030037.</p>
			   <p class="lorem">Churikova, T.G., Gordeychik, B.N., Ivanov, B.V. and Wörner, G., 2013a. Relationship between Kamen Volcano and the Klyuchevskaya group of volcanoes (Kamchatka). Journal of Volcanology and Geothermal Research, 263, 3-21. https://doi.org/10.1016/j.jvolgeores.2013.01.019.</p>
			   <p class="lorem">Churikova, T.G., Ivanov, B.V., Eichelberger, J., Wörner, G., Browne, B. and Izbekov, P., 2013b. Major and trace element zoning in plagioclase from Kizimen Volcano (Kamchatka): Insights into magma-chamber processes. Journal of Volcanology and Seismology, 7(2), 112-130. https://doi.org/10.1134/S0742046313020024.</p>
			   <p class="lorem">Churikova, T.G., Gordeychik, B.N., Edwards, B.R., Ponomareva, V.V. and Zelenin, E.A., 2015a. The Tolbachik volcanic massif: A review of the petrology, volcanology and eruption history prior to the 2012-2013 eruption. Journal of Volcanology and Geothermal Research, 307, 3-21. https://doi.org/10.1016/j.jvolgeores.2015.10.016.</p>
			   <p class="lorem">Churikova, T.G., Gordeychik, B.N., Iwamori, H., Nakamura, H., Ishizuka, O., Nishizawa, T., Haraguchi, S., Miyazaki, T. and Vaglarov, B.S., 2015b. Petrological and geochemical evolution of the Tolbachik volcanic massif, Kamchatka, Russia. Journal of Volcanology and Geothermal Research, 307, 156-181. https://doi.org/10.1016/j.jvolgeores.2015.10.026.</p>
			   <p class="lorem">Davydova, M.Y., Martynov, Y.A. and Perepelov, A.B., 2019. Evolution of the isotopic-geochemical composition of rocks of Uksichan volcano, Sredinnyi Range, Kamchatka, and its relations to the tectonic restyling of Kamchatka in the Neogene. Petrology, 27(3), 265-290. https://doi.org/10.1134/S0869591119030020.</p>
			   <p class="lorem">Dirksen, O.V. and Melekestsev, I.V., 1998. Monogenetic volcanism at the vicinity of Bakening volcano (Kamchatka, Russia). In: B.V. Ivanov (Ed.) Recent volcanism of the Kurile-Kamchatkan and Alaska-Aleutian island arcs: The questions of volcanic hazard, tsunami hazard, magma genesis, earthquakes, geodynamics: comparative analyses. Abstracts of international seismic volcanic workshop on Kamchatkan-Aleutian subduction processes. Petropavlovsk-Kamchatsky, July 1-9, 1998. IVGG FED RAS, Petropavlovsk-Kamchatsky, pp. 35-36.</p>
			   <p class="lorem">Dirksen, O., Humphreys, M.C.S., Pletchov, P., Melnik, O., Demyanchuk, Y., Sparks, R.S.J. and Mahony, S., 2006. The 2001–2004 dome-forming eruption of Shiveluch volcano, Kamchatka: Observation, petrological investigation and numerical modelling. Journal of Volcanology and Geothermal Research, 155(3), 201-226. https://doi.org/10.1016/j.jvolgeores.2006.03.029.</p>
			   <p class="lorem">Dorendorf, F., Churikova, T., Koloskov, A. and Wörner, G., 2000a. Late Pleistocene to Holocene activity at Bakening volcano and surrounding monogenetic centers (Kamchatka): volcanic geology and geochemical evolution. Journal of Volcanology and Geothermal Research, 104(1), 131-151. https://doi.org/10.1016/S0377-0273(00)00203-1.</p>
			   <p class="lorem">Dorendorf, F., Wiechert, U. and Wörner, G., 2000b. Hydrated sub-arc mantle: a source for the Kluchevskoy Volcano, Kamchatka/Russia. Earth and Planetary Science Letters, 175(1–2), 69-86. https://doi.org/10.1016/S0012-821X(99)00288-5.</p>
			   <p class="lorem">Dosseto, A., Bourdon, B., Joron, J.-L. and Dupré, B., 2003. U-TH-PA-RA study of the Kamchatka arc: new constraints on the genesis of arc lavas. Geochimica et Cosmochimica Acta, 67(15), 2857-2877. http://dx.doi.org/10.1016/S0016-7037(03)00086-3.</p>
			   <p class="lorem">Erlich, E.N., 1966. Central kamchatkan depression. In: E.N. Erlich (Ed.) Petrochemistry of the Cenozoic Kuril-Kamchatka volcanic province. Nauka, Moscow, pp. 105-134. https://search.rsl.ru/ru/record/01006222022. (In Russian).</p>
			   <p class="lorem">Ermakov, V.A., 1977. Formation dismemberment of the Quaternary volcanic rocks. Nedra, Moscow, 223 pp., http://repo.kscnet.ru/1055/. (In Russian).</p>
			   <p class="lorem">Ermakov, V.A., 1978. Petrology and origin of basalts in the regional zone of cinder cones of the Tolbachinsky Dol. In: T.I. Frolova and V.A. Ermakov (Eds.), Petrological studies of island arc mafic rocks. Institute of Physics of the Earth, Academy of Sciences of the USSR, Moscow, pp. 3-68. https://www.geokniga.org/books/23447. (In Russian).</p>
			   <p class="lorem">Ermakov, V.A. and Vazheevskaya, A.A., 1973. Volcanoes Ostry and Plosky Tolbachik. Bulletin of volcanological stations, (49), 43-53. (In Russian).</p>
			   <p class="lorem">Ermakov, V.A., Gontovaya, L.I. and Senyukov, S.L., 2013. Preliminary model of the new Tolbachik eruption (50 years of IVS), obtained from a complex of geological and geophysical data. In: E.I. Gordeev (Ed.) Volcanism and related processes. Regional scientific conference dedicated to the Day of the Volcanologist, Petropavlovsk-Kamchatsky, March 29-30, 2013. Materials of the conference. IVS FEB RAS, Petropavlovsk-Kamchatsky, pp. 63-72. http://www.kscnet.ru/ivs/publication/volc_day/2013/art10.pdf. (In Russian).</p>
			   <p class="lorem">Ermakov, V.A., Gontovaya, L.I. and Senyukov, S.L., 2014. Tectonics and magma chambers of the recent Tolbachik Fissure Eruption (Kamchatka Peninsula). Izvestiya, Atmospheric and Oceanic Physics, 50(8), 745-765. https://doi.org/10.1134/S0001433814080039.</p>
			   <p class="lorem">Fedotov, S.A. and Masurenkov, Y.P. (Eds.).1991. Active volcanoes of Kamchatka. In 2 volumes.  Nauka, Moscow. http://repo.kscnet.ru/158/.</p>
			   <p class="lorem">Flerov, G.B. and Melekestsev, I.V., 2013. 2012–2013 eruption as a result of ongoing activity of the Tolbachik regional zone of scoria cones (Klyuchevskaya group of volcanoes, Kamchatka). In: E.I. Gordeev (Ed.) Volcanism and related processes. Regional scientific conference dedicated to the Day of the Volcanologist, Petropavlovsk-Kamchatsky, March 29-30, 2013. Materials of the conference. IVS FEB RAS, Petropavlovsk-Kamchatsky, pp. 139-144. http://www.kscnet.ru/ivs/publication/volc_day/2013/art20.pdf. (In Russian).</p>
			   <p class="lorem">Flerov, G.B. and Ovsyannikov, A.A., 1991. Ushkovsky Volcano. In: S.A. Fedotov and Y.P. Masurenkov (Eds.), Active Volcanoes of Kamchatka. In 2 volumes. Vol. 1. Nauka, Moscow, pp. 154-165.</p>
			   <p class="lorem">Flerov, G.B., Andreev, V.N., Budnikov, V.A. and Tsyurupa, A.I., 1984. Petrology of the eruption products. In: S.A. Fedotov (Ed.) Large Tolbachik Fissure Eruption. Kamchatka. 1975–1976. Nauka, Moscow, pp. 223-284. http://repo.kscnet.ru/541/1/btti1975-1976.djvu. (In Russian).</p>
			   <p class="lorem">Flerov, G.B., Fedorov, P.I. and Churikova, T.G., 2001. Geochemistry of Late Cretaceous-Paleogene potassic rocks of the early evolutionary stage in the Kamchatka island arc. Petrology, 9(2), 161-178. http://elibrary.ru/item.asp?id=13379921.</p>
			   <p class="lorem">Flerov, G.B., Anan’ev, V.V. and Ponomarev, G.P., 2015. The petrogenesis of rocks of the Ostryi and Ploskii volcanoes and the relationship between volcanic occurrences of basaltic and trachybasaltic magmas in the Tolbachik Dol area, Kamchatka. Journal of Volcanology and Seismology, 9(3), 162-181. https://doi.org/10.1134/S0742046315030021.</p>
			   <p class="lorem">Flerov, G.B., Churikova, T.G. and Anan'ev, V.V., 2017. The Ploskie Sopki volcanic massif: Geology, petrochemistry, mineralogy, and petrogenesis (Klyuchevskoi Volcanic Cluster, Kamchatka). Journal of Volcanology and Seismology, 11(4), 266-284. https://doi.org/10.1134/S0742046317040030.</p>
			   <p class="lorem">Flerov, G.B., Churikova, T.G., Gordeychik, B.N. and Ananyev, V.V., 2019. The Ziminy Sopki Volcanic Massif: geology and mineralogy of rocks (The Klyuchevskoy Volcanic Group, Kamchatka). Vestnik KRAUNTs. Nauki o Zemle, 44(4), 19-34. https://doi.org/10.31431/1816-5524-2019-4-44-19-34. (In Russian).</p>
			   <p class="lorem">Frolova, T.I., Bindeman, I.N., Mahmoud, M. and Bailey, J.C., 1992. Melanocratic inclusions in andesites and dacites of the Kurile-Kamchatka volcanic arc. International Geology Review, 34(2), 119-130. https://doi.org/10.1080/00206819209465588.
			   <p class="lorem">Hedge, C.E. and Gorshkov, G.S., 1977. Strontium-isotope composition of volcanic rocks from Kamchatka. Doklady Akademii Nauk SSSR, 233, 69-166.</p>
			   <p class="lorem">Hochstaedter, A.G., Kepezhinskas, P., Defant, M., Drummond, M. and Koloskov, A., 1996. Insights into the volcanic arc mantle wedge from magnesian lavas from the Kamchatka arc. Journal of Geophysical Research: Solid Earth, 101(B1), 697-712. https://doi:10.1029/95JB02404.</p>
			   <p class="lorem">Ishikawa, T., Tera, F. and Nakazawa, T., 2001. Boron isotope and trace element systematics of the three volcanic zones in the Kamchatka arc. Geochimica et Cosmochimica Acta, 65(24), 4523-4537. https://doi.org/10.1016/S0016-7037(01)00765-7.</p>
			   <p class="lorem">Ivanov, B.V., 2008. Andesites of Kamchatka (Reference guide to the chemical analysis of volcanites and basic rock-forming minerals). Nauka, Moscow, 365 pp., http://www.kscnet.ru/ivs/publication/ivanov/Andesites_of_Kamchatka.pdf. (In Russian).</p>
			   <p class="lorem">Ivanov, A.V., Perepelov, A.B., Puzankov, M.Y., Yasnygina, T.A., Malykh, Y.M. and Rasskazov, S.V., 2004. Rift- and arc-type basaltic volcanism of the Sredinny Ridge, Kamchatka: case study of the Payalpan volcano-tectonic structure In: A.I. Khanchuk, G.A. Gonevchuk, A.N. Mitrokhin, L.F. Simanenko, N.J. Cook and R. Seltmann (Eds.), Metallogeny of the Pacific Northwest: Tectonics, Magmatism and Metallogeny of Active Continental Margins. Proceedings of the interim IAGOD-Conference Vladivostok/Russia: 1-20 September 2004. Dalnauka, Vladivostok, pp. 345-349. https://www.schweizerbart.de/publications/detail/isbn/9783510654109/Tectonics_Magmatism_and_Metallogeny_.</p>
			   <p class="lorem">Ivanov, A.V., Perepelov, A.B., Palesskii, S.V. and Nikolaeva, I.V., 2008. First data on the distribution of platinum group elements (Ir, Os, Ru, Pt, and Pd) and Re in island-arc basalts of Kamchatka. Doklady Earth Sciences, 420(4), 597–601. https://doi.org/10.1134/S1028334X08040168.</p>
			   <p class="lorem">Iveson, A., Humphreys, M.C., Savov, I.P., de Hoog, C.-J.M., Turner, S.J., Churikova, T.G., Macpherson, C.G., Mather, T.A., Gordeychik, B.N., Tomanikova, L., Agostini, S., Hammond, K., Pyle, D. and Cooper, G.F., 2021. Deciphering variable mantle sources and hydrous inputs to arc magmas in Kamchatka. Earth and Planetary Science Letters, 562, art. 116848, 1-15. https://doi.org/10.1016/j.epsl.2021.116848.</p>
			   <p class="lorem">Iveson, A.A., Humphreys, M., Jenner, F.E., Kunz, B.E., Savov, I.P., de Hoog, C.-J.M., Churikova, T.G., Gordeychik, B.N., Hammond, S.J., Plechov, P.Y., Blundy, J. and Agostini, S., 2022. Tracing volatiles, halogens, and chalcophile metals during melt evolution at monogenetic cones of the Tolbachik volcanic massif, Kamchatka. Journal of Petrology, 63(9), art. egac087, 1-22. https://doi.org/10.1093/petrology/egac087.</p>
			   <p class="lorem">Kamenetsky, V.S., Zelenski, M., Gurenko, A., Portnyagin, M., Ehrig, K., Kamenetsky, M., Churikova, T. and Feig, S., 2017. Silicate-sulfide liquid immiscibility in modern arc basalt (Tolbachik volcano, Kamchatka): Part II. Composition, liquidus assemblage and fractionation of the silicate melt. Chemical Geology, 471, 92-110. https://doi.org/10.1016/j.chemgeo.2017.09.019.</p>
			   <p class="lorem">Kamenetsky, V.S., Zelenski, M., Gurenko, A., Portnyagin, M., Ehrig, K., Kamenetsky, M., Churikova, T. and Feig, S., 2018. Reprint of Silicate-sulfide liquid immiscibility in modern arc basalt (Tolbachik volcano, Kamchatka): Part II. Composition, liquidus assemblage and fractionation of the silicate melt. Chemical Geology, 478, 112-130. https://doi.org/10.1016/j.chemgeo.2017.10.026.</p>
			   <p class="lorem">Kay, R.W., 1978. Aleutian magnesian andesites: Melts from subducted Pacific ocean crust. Journal of Volcanology and Geothermal Research, 4(1-2), 117-132. https://doi.org/10.1016/0377-0273(78)90032-X.</p>
			   <p class="lorem">Kepezhinskas, P., McDermott, F., Defant, M.J., Hochstaedter, A., Drummond, M.S., Hawkesworth, C.J., Koloskov, A., Maury, R.C. and Bellon, H., 1997. Trace element and SrNdPb isotopic constraints on a three-component model of Kamchatka Arc petrogenesis. Geochimica et Cosmochimica Acta, 61(3), 577-600. https://doi.org/10.1016/S0016-7037(96)00349-3.</p>
			   <p class="lorem">Kersting, A.B. and Arculus, R.J., 1994. Klyuchevskoy Volcano, Kamchatka, Russia: The role of high-flux recharged, tapped, and fractionated magma chamber(s) in the genesis of high-Al2O3 from high-MgO basalt. Journal of Petrology, 35(1), 1-41. https://doi.org/10.1093/petrology/35.1.1.</p>
			   <p class="lorem">Kersting, A.B. and Arculus, R.J., 1995. Pb isotope composition of Klyuchevskoy volcano, Kamchatka and North Pacific sediments: Implications for magma genesis and crustal recycling in the Kamchatkan arc. Earth and Planetary Science Letters, 136(3), 133-148. https://doi.org/10.1016/0012-821X(95)00196-J.</p>
			   <p class="lorem">Khrenov, A.P., Antipin, V.C., Chuvashova, L.A. and Smirnova, E.B., 1989. Petrochemical and geochemical featuress of bassalts from Klyuchevskoi. Volkanologiya i Seismologiya, (3), 3-15. http://repo.kscnet.ru/2879/1/VS-3_1989pgb.pdf. (In Russian).</p>
			   <p class="lorem">Khrenov, A.P., Dvigalo, V.N., Kirsanov, I.T., Fedotov, S.A., Gorelchik, V.I. and Zharinov, N.A., 1991. Klyuchevskoy Volcano. In: S.A. Fedotov and Y.P. Masurenkov (Eds.), Active Volcanoes of Kamchatka. In 2 volumes. Vol. 1. Nauka, Moscow, pp. 106–153. http://repo.kscnet.ru/id/eprint/3988.</p>
			   <p class="lorem">Khubunaya, S.A., Bogoyavlenskiy, S.O., Novgorodtseva, T.Y. and Okrugina, A.I., 1993. The mineralogy of the Klyuchevskoi magnesian basalts depicting the fractionation in the magma chamber. Volkanologiya i Seismologiya, (3), 46-69. http://repo.kscnet.ru/2137/. (In Russian).</p>
			   <p class="lorem">Khubunaya, S.A., Eremina, T.S. and Sobolev, A.V., 2016. The classification of potassium basaltic trachyandesites that were discharged by the 2012–2013 parasitic eruption on Ploskii Tolbachik Volcano, Kamchatka using geochemical criteria. Journal of Volcanology and Seismology, 10(1), 33-49. https://doi.org/10.1134/S0742046316010024.</p>
			   <p class="lorem">Koloskov, A.V., Flerov, G.B., Seliverstov, V.A., Dorendorf, F. and Churikova, T.G., 1999. Potassic volcanics of the Central Kamchatka and the Late-Cretaceous-Palaeogene Kuril-Kamchatka alcaline province. Petrology, 7(5), 527-543. http://elibrary.ru/item.asp?id=13332053.</p>
			   <p class="lorem">Koloskov, A.V., Flerov, G.B. and Golubev, V.N., 2001. First Sm–Nd isotope data on clinopyroxenes from Late Cretaceous–Paleogene alkaline magmatic rocks of Central Kamchatka. Doklady Earth Sciences, 376(1), 51-53. https://elibrary.ru/item.asp?id=13817743.</p>
			   <p class="lorem">Koloskov, A.V., Flerov, G.B., Perepelov, A.B., Melekestsev, I.V., Puzankov, M.Y. and Filosofova, T.M., 2011. Evolution stages and petrology of the Kekuknai volcanic massif as reflecting the magmatism in Backarc zone of Kuril-Kamchatka island arc system. Part 1. Geological position and geochemistry of volcanic rocks. Journal of Volcanology and Seismology, 5(5), 312-334. https://doi.org/10.1134/S074204631104004X.</p>
			   <p class="lorem">Koloskov, A.V., Davydova, M.Y., Izbekov, P.E., Ananyev, V.V. and Kandrin, A.A., 2015. Evolution of rock compositions observed during the 2012–2013 eruptions of the New Tolbachik volcanoes: Online mantle control. Russian Journal of Pacific Geology, 9(5), 338-358. https://doi.org/10.1134/S1819714015050036.</p>
			   <p class="lorem">Koloskov, A.V., Davydova, M.Y., Anan’ev, V.V. and Kandrin, A.A., 2017. The Tolbachik Volcanic Center: The composition of ejecta, phases of activity, a petrologic model. Journal of Volcanology and Seismology, 11(4), 235-265. https://doi.org/10.1134/S0742046317040042.</p>
			   <p class="lorem">Koloskov, A.V., Puzankov, M.Y., Ananiev, V.V. and Kovalenko, D.V., 2022. The Bolshoi Payalpan volcano (Sredinny Range, Kamchatka): problematic aspects of the convergence of island-arc and within-plate petrological and geochemical signatures in the magmatic system. Russian Journal of Pacific Geology, 16(2), 63-82. https://doi.org/10.1134/S1819714022020063.</p>
			   <p class="lorem">Litvinov, A.F., Belii, A.V. and Lopatin, V.B., 1991. Late Cenozoic volcanism in the Ozernoy Peninsula (Eastern Kamchatka). Volcanology and Seismology, (2), 12-27. (In Russian).</p>
			   <p class="lorem">Liu, S.-A., Huang, J., Liu, J., Wörner, G., Yang, W., Tang, Y.-J., Chen, Y., Tang, L., Zheng, J. and Li, S., 2015. Copper isotopic composition of the silicate Earth. Earth and Planetary Science Letters, 427, 95-103. https://doi.org/10.1016/j.epsl.2015.06.061.</p>
			   <p class="lorem">Melekestsev, I.V., Volynets, O.N., Ermakov, V.A., Kirsanova, T.P. and Masurenkov, Y.P., 1991. Sheveluch Volcano. In: S.A. Fedotov and Y.P. Masurenkov (Eds.), Active Volcanoes of Kamchatka. In 2 volumes. Vol. 1. Nauka, Moscow, pp. 82-103. http://repo.kscnet.ru/2256/.</p>
			   <p class="lorem">Mironov, N.L. and Portnyagin, M.V., 2018. Coupling of Redox Conditions of Mantle Melting and Copper and Sulfur Contents in Primary Magmas of the Tolbachinsky Dol (Kamchatka) and Juan de Fuca Ridge (Pacific Ocean). Petrology, 26(2), 145-166. https://doi.org/10.1134/s0869591118020030.</p>
			   <p class="lorem">Münker, C., Wörner, G., Yogodzinski, G. and Churikova, T., 2004. Behaviour of high field strength elements in subduction zones: constraints from Kamchatka–Aleutian arc lavas. Earth and Planetary Science Letters, 224(3), 275-293. https://doi.org/10.1016/j.epsl.2004.05.030.</p>
			   <p class="lorem">Nekrylov, N.A., Plechov, P.Y., Bychkov, K.A., Perepelov, A.B., Puzankov, M.Y., Shur, M.Y., Dirksen, O.V. and Bazanova, L.I., 2015. Parental melts of the last volcanic pulse in the Sedanka field, Sredinny Range, Kamchatka. Moscow University Geology Bulletin, 70(3), 233-239. https://doi.org/10.3103/S0145875215030060.</p>
			   <p class="lorem">Nekrylov, N.A., Popov, D.V., Plechov, P.Y., Shcherbakov, V.D., Danyushevsky, L.V. and Dirksen, O.V., 2018. Garnet-Pyroxenite-Derived End-Member Magma Type in Kamchatka: Evidence from Composition of Olivine and Olivine-Hosted Melt Inclusions in Holocene Rocks of Kekuknaisky Volcano. Petrology, 26(4), 329-350. https://doi.org/10.1134/S0869591118040057.</p>
			   <p class="lorem">Nekrylov, N., Popov, D.V., Plechov, P.Y., Shcherbakov, V.D. and Danyushevsky, L.V., 2021. The origin of the Late Quaternary back-arc volcanic rocks from Kamchatka: evidence from the compositions of olivine and olivine-hosted melt inclusions. Contributions to Mineralogy and Petrology, 176(9), 71. https://doi.org/10.1007/s00410-021-01830-4.</p>
			   <p class="lorem">Nishizawa, T., Nakamura, H., Churikova, T., Gordeychik, B., Ishizuka, O., Haraguchi, S., Miyazaki, T., Vaglarov, B.S., Chang, Q., Hamada, M., Kimura, J.-I., Ueki, K., Toyama, C., Nakao, A. and Iwamori, H., 2017. Genesis of ultra-high-Ni olivine in high-Mg andesite lava triggered by seamount subduction. Scientific Reports, 7(1): art. 11515, 1-11. https://doi.org/10.1038/s41598-017-10276-3.</p>
			   <p class="lorem">Noll, P.D., Newsom, H.E., Leeman, W.P. and Ryan, J.G., 1996. The role of hydrothermal fluids in the production of subduction zone magmas: Evidence from siderophile and chalcophile trace elements and boron. Geochimica et Cosmochimica Acta, 60(4), 587-611. https://doi.org/10.1016/0016-7037(95)00405-X.</p>
			   <p class="lorem">Ozerov, A.Y., 2000. The evolution of high-alumina basalts of the Klyuchevskoy volcano, Kamchatka, Russia, based on microprobe analyses of mineral inclusions. Journal of Volcanology and Geothermal Research, 95(1), 65-79. https://doi.org/10.1016/S0377-0273(99)00118-3.</p>
			   <p class="lorem">Ozerov, A.Y., Ariskin, A.A., Kyle, P., Bogoyavlenskaya, G.E. and Karpenko, S.F., 1997. Petrological–geochemical model for genetic relationships between basaltic and andesitic magmatism of Klyuchevskoi and Bezymyannyi volcanoes, Kamchatka. Petrology, 5(6), 550-569. https://www.researchgate.net/publication/279179433.</p>
			   <p class="lorem">Pevzner, M.M., 2004. New data on Holocene monogenetic volcanism of the Northern Kamchatka: ages and space distribution. In: E.I. Gordeev (Ed.) Linkages among Tectonics, Seismicity, Magma Genesis, and Eruption in Volcanic Arcs. IV International Biennial Workshop on Subduction Processes Emphasizing the Japan–Kurile–Kamchatka–Aleutian Arcs. Petropavlovsk-Kamchatsky, August 21-27, 2004. Institute of Volcanology and Seismology FEB RAS, Petropavlovsk-Kamchatsky, pp. 72-74. http://www.kscnet.ru/ivs/conferences/kasp/tez/ab34en.doc.</p>
			   <p class="lorem">Pevzner, M.M., 2010. The northern boundary of volcanic activity of Kamchatka in Holocene. Vestnik KRAUNTs. Nauki o Zemle, 15(1), 117-144. http://www.kscnet.ru/journal/kraesc/article/viewFile/478. http://www.kscnet.ru/journal/kraesc/article/viewFile/478. (In Russian).</p>
			   <p class="lorem">Pevzner, M.М., 2015. Holocene Volcanism of Sredinny Range of Kamchatka. M.A. Fedonkin (Ed.). GEOS, Moscow, 252 pp. Transactions of the Geological Institute. Vol. 608. http://www.rfbr.ru/rffi/ru/books/o_1939117#1. (In Russian).</p>
			   <p class="lorem">Pevzner, M.M., Volynets, A.O., Lebedev, V.A., Babansky, A.D., Kovalenko, D.V., Kostitsin, Y.A., Tolstykh, M.L. and Kuscheva, Y.A., 2017. The beginning of volcanic activity within Sredinny metamorphic massif (Sredinny Range, Kamchatka). Doklady Earth Sciences, 475(2), 858-862. https://doi.org/10.1134/S1028334X17080189.</p>
			   <p class="lorem">Pevzner, M.M., Volynets, A.O., Kuscheva, Y.V., Tolstykh, M.L. and Babansky, A.D., 2018. Miocene-Pliocene volcanism of the southeastern flank of the Sredinny Range of Kamchatka (massif of Zagadka Mt.): age and some features of the rocks' composition. In: Methods and Geological Results of the Research of the Isotopic Geochronological Systems of Minerals and Rocks. Proceedings of the Russian conference on Isotope Geochemistry. Moscow, 5-7 June 2018. IGEM RAS, Moscow, pp. 249-251. http://www.geokhi.ru/Lists/List1/Attachments/8552/%D0%93%D0%B5%D0%BE%D1%85%D1%80%D0%BE%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F-2018.pdf. (In Russian).</p>
			   <p class="lorem">Pilipchuk, N.A., Uspensky, V.S., Krikun, N.F. and Nikolaeva, V.I., 2006. The state geologic map of the Russian Federation, scale 1: 200 000, Eastern Kamchatka Series, sheet O-57-XXX. Explanation notes. VSEGEI, St.-Peterburg, 132 pp. (In Russian).</p>
			   <p class="lorem">Pineau, F., Semet, M.P., Grassineau, N., Okrugin, V.M. and Javoy, M., 1999. The genesis of the stable isotope (O, H) record in arc magmas: the Kamtchatka's case. Chemical Geology, 153(1), 93-124. https://doi.org/10.1016/S0009-2541(98)00154-5.</p>
			   <p class="lorem">Pokrovskii, B.G. and Volynets, O.N., 1999. Oxygen isotope geochemistry of extrusive rocks of the Kurile-Kamchatka arc. Petrology, 7(3), 223-245. https://elibrary.ru/item.asp?id=13309305.</p>
			   <p class="lorem">Ponomareva, V., Kyle, P., Pevzner, M., Sulerzhitsky, L. and Hartman, M., 2007. Holocene eruptive history of Shiveluch volcano, Kamchatka peninsula, Russia. In: J. Eichelberger, E. Gordeev, P. Izbekov, M. Kasahara and J. Lees (Eds.), Volcanism and subduction: The Kamchatka region. Geophysical Monograph Series. Vol. 172. American Geophysical Union, pp. 263-282. https://doi.org/10.1029/172GM19.</p>
			   <p class="lorem">Ponomareva, V., Portnyagin, M., Derkachev, A., Pendea, I.F., Bourgeois, J., Reimer, P.J., Garbe-Sch?nberg, D., Krasheninnikov, S. and N?rnberg, D., 2013. Early Holocene M~6 explosive eruption from Plosky volcanic massif (Kamchatka) and its tephra as a link between terrestrial and marine paleoenvironmental records. International Journal of Earth Sciences, 102(6), 1673-1699. https://doi.org/10.1007/s00531-013-0898-0.</p>
			   <p class="lorem">Portnyagin, M., Hoernle, K., Avdeiko, G., Hauff, F., Werner, R., Bindeman, I., Uspensky, V. and Garbe-Schönberg, D., 2005. Transition from arc to oceanic magmatism at the Kamchatka-Aleutian junction. Geology, 33(1), 25-28. https://doi.org/10.1130/g20853.1.</p>
			   <p class="lorem">Portnyagin, M., Bindeman, I., Hoernle, K. and Hauff, F., 2007a. Geochemistry of primitive lavas of the Central Kamchatka Depression: magma generation at the edge of the Pacific Plate. In: J. Eichelberger, E. Gordeev, P. Izbekov, M. Kasahara and J. Lees (Eds.), Volcanism and Subduction: The Kamchatka Region. Geophysical Monograph Series. Vol. 172. American Geophysical Union, Washington, DC, pp. 199-239. http://doi.org/10.1029/172GM16.</p>
			   <p class="lorem">Portnyagin, M., Hoernle, K., Plechov, P., Mironov, N. and Khubunaya, S., 2007b. Constraints on mantle melting and composition and nature of slab components in volcanic arcs from volatiles (H2O, S, Cl, F) and trace elements in melt inclusions from the Kamchatka Arc. Earth and Planetary Science Letters, 255(1), 53-69. https://doi.org/10.1016/j.epsl.2006.12.005.</p>
			   <p class="lorem">Portnyagin, M., Duggen, S., Hauff, F., Mironov, N., Bindeman, I., Thirlwall, M. and Hoernle, K., 2015. Geochemistry of the late Holocene rocks from the Tolbachik volcanic field, Kamchatka: Quantitative modelling of subduction-related open magmatic systems. Journal of Volcanology and Geothermal Research, 307, 133-155. https://doi.org/10.1016/j.jvolgeores.2015.08.015.</p>
			   <p class="lorem">Portnyagin, M.V., Mironov, N.L. and Nazarova, D.P., 2017. Copper partitioning between olivine and melt inclusions and its content in primitive island-arc magmas of Kamchatka. Petrology, 25(4), 419-432. http://doi.org/10.1134/s086959111704004x.</p>
			   <p class="lorem">Puzankov, M.Y., Shipitsyn, Y.G. and Bobrov, V.A., 1990. Geochemical typification of igneous and metamorphic rocks of Kamchatka. A.P. Krivenko (Ed.). Institute of geology and geophysics, AN SSSR, Siberian Branch, Novosibirsk, 259 pp. Transactions of the Institute of Geology and Geophysics of the Siberian Branch of the USSR Academy of Sciences; Vol. 390. https://search.rsl.ru/ru/record/01002123232. (In Russian).</p>
			   <p class="lorem">Tatsumi, Y., Kogiso, T. and Nohda, S., 1995. Formation of a third volcanic chain in Kamchatka: generation of unusual subduction-related magmas. Contributions to Mineralogy and Petrology, 120(2), 117-128. https://doi.org/10.1007/BF00287109.</p>
			   <p class="lorem">Titaeva, N.A., Ermakov, V.A., Zozulya, T.A., Stavrov, O.D. and Chekhovskikh, M.M., 1978. Geochemical types of basalts from the Great fissure Tolbachik eruption of 1975-1976. In: T.I. Frolova and V.A. Ermakov (Eds.), Petrological studies of island arc mafic rocks. Institute of Physics of the Earth, Academy of Sciences of the USSR, Moscow, pp. 69-109. https://www.geokniga.org/books/23447. (In Russian).</p>
			   <p class="lorem">Turner, S., McDermott, F., Hawkesworth, C. and Kepezhinskas, P., 1998. A U-series study of lavas from Kamchatka and the Aleutians: constraints on source composition and melting processes. Contributions to Mineralogy and Petrology, 133(3), 217-234. https://doi.org/10.1007/s004100050449.</p>
			   <p class="lorem">Turner, S., Sims, K.W.W., Reagan, M. and Cook, C., 2007. A 210Pb–226Ra–230Th–238U study of Klyuchevskoy and Bezymianny volcanoes, Kamchatka. Geochimica et Cosmochimica Acta, 71(19), 4771-4785. https://doi.org/10.1016/j.gca.2007.08.006.</p>
			   <p class="lorem">Vazheevskaya, A.A., Ogorodov, N.V. and Ogorodova, A.S., 1972. Petrography, petrochemistry and trace elements. In: E.N. Erlich (Ed.) Volcanoes and Quaternary volcanism of the Sredinny Range of Kamchatka. Nauka, Moscow, pp. 38-95. http://geo.web.ru/db/msg.html?mid=1178923. (In Russian).</p>
			   <p class="lorem">Vlodavets, V.I., 1940. Klyuchevskaya group of volcanoes. F.Y. Levinson-Lessing (Ed.). Publishing house of the Academy of Sciences of the USSR, Moscow, Leningrad, 124 pp. Transactions of the Kamchatka volcanological station. Vol. 1. http://www.kscnet.ru/ivs/bibl/trudikv/tkv1.djvu. (In Russian).</p>
			   <p class="lorem">Volynets, O.N., 1994. Geochemical types, petrology, and genesis of Late Cenozoic volcanic rocks from the Kurile-Kamchatka island-arc system. International Geology Review, 36(4), 373-405. https://doi.org/10.1080/00206819409465467.</p>
			   <p class="lorem">Volynets, O.N., Patoka, M.G., Melekestsev, I.V. and Zubin, M.I., 1991. Ichinsky Volcano. In: S.A. Fedotov and Y.P. Masurenkov (Eds.), Active Volcanoes of Kamchatka. In 2 volumes. Vol. 1. Nauka, Moscow, pp. 280-294. http://repo.kscnet.ru/1807/.</p>
			   <p class="lorem">Volynets, O.N., Koloskov, A.V., Seliverstov, N.I., Yagodzhinski, Y., Egorov, Y.O., Shkira, V.A. and Churikova, T.G., 1994. New evidence on backarc volcanism in the Eastern Aleutians. Volcanology and Seismology, 15(4), 443-468. https://www.researchgate.net/publication/309809674.</p>
			   <p class="lorem">Volynets, O.N., Ponomareva, V.V. and Babansky, A.D., 1997. Magnesian basalts of Shiveluch andesite volcano, Kamchatka. Petrology, 5(2), 183-196. http://repo.kscnet.ru/3757/.</p>
			   <p class="lorem">Volynets, O.N., Melekestsev, I.V., Ponomareva, V.V. and Yogodzinski, G.M., 1999. Kharchinsky and Zarechnyi volcanoes - unique centers of Late Pleistocene magnesian basalts in Kamchatka: structural setting, morphology, geologic structure and age. Volcanology and Seismology, 20(4-5), 383-399. http://repo.kscnet.ru/1139/.</p>
			   <p class="lorem">Volynets, O.N., Babanskii, A.D. and Gol’tsman, Y.V., 2000. Variations in isotopic and trace-element composition of lavas from volcanoes of the Northern Group, Kamchatka, in relation to specific features of subduction. Geochemistry International, 38(10), 974-989. https://elibrary.ru/item.asp?id=13340929; http://www.kscnet.ru/ivs/bibl/sotrudn/stvolinez/Volynets_2000%20Geochimia%20engl.pdf.</p>
			   <p class="lorem">Volynets, A.O., Churikova, T.G., Wörner, G., Gordeychik, B.N. and Layer, P., 2010. Mafic Late Miocene–Quaternary volcanic rocks in the Kamchatka back arc region: implications for subduction geometry and slab history at the Pacific–Aleutian junction. Contributions to Mineralogy and Petrology, 159(5), 659-687. https://doi.org/10.1007/s00410-009-0447-9.</p>
			   <p class="lorem">Volynets, A.O., Melnikov, D.V. and Yakushev, A.I., 2013. First data on composition of the volcanic rocks of the IVS 50th anniversary Fissure Tolbachik eruption (Kamchatka). Doklady Earth Sciences, 452(1), 953-957. https://doi.org/10.1134/S1028334X13090201.</p>
			   <p class="lorem">Volynets, A.O., Edwards, B.R., Melnikov, D., Yakushev, A. and Griboedova, I., 2015. Monitoring of the volcanic rock compositions during the 2012–2013 fissure eruption at Tolbachik volcano, Kamchatka. Journal of Volcanology and Geothermal Research, 307, 120-132. https://doi.org/10.1016/j.jvolgeores.2015.07.014.</p>
			   <p class="lorem">Volynets, A.O., Pevzner, M.M., Lebedev, V.A., Tolstykh, M.L. and Babansky, A.D., 2018. Stages of activity of the Akhtang volcanic massif (Sredinny Range of Kamchatka) in Neogene–Quaternary. In: Methods and Geological Results of the Research of the Isotopic Geochronological Systems of Minerals and Rocks. Proceedings of the Russian conference on Isotope Geochemistry. Moscow, 5-7 June 2018. IGEM RAS, Moscow, pp. 80-82. http://www.geokhi.ru/Lists/List1/Attachments/8552/%D0%93%D0%B5%D0%BE%D1%85%D1%80%D0%BE%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F-2018.pdf. (In Russian).</p>
			   <p class="lorem">Volynets, A.O., Pevzner, M.M., Tolstykh, M.L. and Babansky, A.D., 2018b. Volcanism of the southern part of the Sredinny Range of Kamchatka in the Neogene-Quaternary. Russian Geology and Geophysics, 59(12), 1577-1591. https://doi.org/10.1016/j.rgg.2018.12.004.</p>
			   <p class="lorem">Yogodzinski, G.M., Kay, R.W., Volynets, O.N., Koloskov, A.V. and Kay, S.M., 1995. Magnesian andesite in the western Aleutian Komandorsky region: Implications for slab melting and processes in the mantle wedge. GSA Bulletin, 107(5), 505-519. https://doi.org/10.1130/0016-7606(1995)107<0505:MAITWA>2.3.CO;2.</p>`;
			   
var contentCredits = `<br><hr><h2>Credits</h2>
<p class="lorem">The webb-map is built using the awesome open-source JavaScript library <a href="https://leafletjs.com/" target="_blank">Leaflet</a>. 
Besides, it makes use of a set of Leaflet plugins (incl. <a href=”https://esri.github.io/esri-leaflet/” target="_blank">ESRI for Leaflet</a>) and ArcGIS basemaps - 
Topographic and <a href="https://hub.arcgis.com/datasets/39858979a6ba4cfd96005bbe9bd4cf82" target="_blank">Firefly Imagery</a>. The latter provides a mosaic of satellite and aerial images for the entire world with up to 0.5 m resolution (TerraColor, SPOT and Maxar). 
The basemaps are freely distributed for non-commercial use under Essentials Developer Plan (<a href=”https://github.com/esri/esri-leaflet#terms” target="_blank">ESRI's Terms of Use</a>).</p>\
<br><hr>
<p class="lorem">&copy; 2018-2020 Elena Marchenko<br>PhD Goesciences, Research fellow<br>
Laboratory of Informatic Technologies and Geoecology<br>
<a href="http://www.kscnet.ru/ivs/ target="_blank"">Institute of Volcanology and Seismology</a><br>Far Eastern Branch of Russian Academy of Sciences</p>';
`;

